package com.aheadt1d.app.report

import android.content.Context
import android.graphics.Color
import android.graphics.Paint
import android.graphics.pdf.PdfDocument
import java.io.File
import java.time.Instant
import java.time.ZoneId
import java.time.format.DateTimeFormatter
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext

/**
 * Assembles a ReportData into two separate, standalone PDF files (via
 * android.graphics.pdf.PdfDocument - no extra library needed): a clinical
 * version (numbers + curve only) and an annotated version (same data, plus
 * event notes/tags overlaid) - handed over separately so the doctor
 * conversation dictates which one actually gets shared. Both are built from
 * the exact same ReportData, so they can never drift out of sync with each
 * other.
 *
 * Clean/high-contrast layout on purpose (white background, purple accent
 * only in the header) - this is meant to be printed or read on a doctor's
 * screen, not a branded app screen.
 */
object DoctorReportPdfGenerator {
    // US Letter at 72dpi - PdfDocument's PageInfo units are pixels at that
    // implied density, and this prints cleanly without any scaling surprises.
    private const val PAGE_WIDTH = 612
    private const val PAGE_HEIGHT = 792
    private const val MARGIN = 36f
    private const val CONTENT_WIDTH = PAGE_WIDTH - 2 * MARGIN

    private val PURPLE_ACCENT = Color.parseColor("#6B3FA0")
    private val WARNING_COLOR = Color.parseColor("#E0A030")
    private val MUTED_TEXT = Color.parseColor("#666666")

    data class GeneratedReports(val clinicalFile: File, val annotatedFile: File)

    suspend fun generate(context: Context, data: ReportData): GeneratedReports = withContext(Dispatchers.IO) {
        val slug = dateRangeSlug(data.startDate, data.endDate)
        val clinicalFile = File(context.cacheDir, "ahead-report-clinical-$slug.pdf")
        val annotatedFile = File(context.cacheDir, "ahead-report-annotated-$slug.pdf")

        writeReport(data, showAnnotations = false, title = "Clinical Report", outFile = clinicalFile)
        writeReport(data, showAnnotations = true, title = "Annotated Report", outFile = annotatedFile)

        GeneratedReports(clinicalFile, annotatedFile)
    }

    private fun writeReport(data: ReportData, showAnnotations: Boolean, title: String, outFile: File) {
        val document = PdfDocument()
        val cursor = Cursor(document, initialPageNumber = 1)

        drawHeader(cursor, title, data)
        drawMetricsBlock(cursor, data.metrics)

        val chartWidth = CONTENT_WIDTH.toInt()
        val chartHeight = 260
        cursor.ensureSpace(chartHeight + 24f)
        val chartBitmap = GlucoseReportChartRenderer.renderChart(data, showAnnotations, chartWidth, chartHeight)
        cursor.canvas.drawBitmap(chartBitmap, MARGIN, cursor.y, null)
        cursor.y += chartHeight + 8f
        chartBitmap.recycle()

        drawColorLegend(cursor)

        if (showAnnotations) {
            drawEventLegend(cursor, data.events)
        }

        cursor.finishPage()
        outFile.outputStream().use { document.writeTo(it) }
        document.close()
    }

    private fun drawHeader(cursor: Cursor, title: String, data: ReportData) {
        val zone = ZoneId.systemDefault()
        val rangeText = "${DATE_FORMATTER.withZone(zone).format(data.startDate)} - ${DATE_FORMATTER.withZone(zone).format(data.endDate)}"
        val generatedText = "Generated by Ahead - ${TIMESTAMP_FORMATTER.withZone(zone).format(Instant.now())}"

        val accentBar = Paint().apply { color = PURPLE_ACCENT }
        cursor.canvas.drawRect(MARGIN, cursor.y, MARGIN + CONTENT_WIDTH, cursor.y + 6f, accentBar)
        cursor.y += 22f

        val titlePaint = Paint().apply { color = Color.BLACK; textSize = 22f; isAntiAlias = true; isFakeBoldText = true }
        cursor.canvas.drawText("Ahead - $title", MARGIN, cursor.y, titlePaint)
        cursor.y += 22f

        val subPaint = Paint().apply { color = MUTED_TEXT; textSize = 13f; isAntiAlias = true }
        cursor.canvas.drawText(rangeText, MARGIN, cursor.y, subPaint)
        cursor.y += 18f
        cursor.canvas.drawText(generatedText, MARGIN, cursor.y, subPaint)
        cursor.y += 28f
    }

    private fun drawMetricsBlock(cursor: Cursor, metrics: AgpMetrics) {
        val labelPaint = Paint().apply { color = MUTED_TEXT; textSize = 12f; isAntiAlias = true }
        val valuePaint = Paint().apply { color = Color.BLACK; textSize = 16f; isAntiAlias = true; isFakeBoldText = true }

        if (metrics.isBelowMinimumUsableCoverage || metrics.isBelowRecommendedCoverage) {
            drawCoverageWarning(cursor, metrics)
        }

        val rows = listOf(
            "Mean glucose" to "%.0f mg/dL".format(metrics.meanGlucose),
            "GMI (est. A1C)" to "%.1f%%".format(metrics.gmi),
            "Coefficient of variation" to "%.0f%%".format(metrics.coefficientOfVariation),
            "Time in range (70-180)" to "%.0f%%".format(metrics.timeInRangePercent),
        )
        val rangeBreakdown = listOf(
            "Very low (<54)" to metrics.timeBelowRangeL2Percent,
            "Low (54-69)" to metrics.timeBelowRangeL1Percent,
            "High (181-250)" to metrics.timeAboveRangeL1Percent,
            "Very high (>250)" to metrics.timeAboveRangeL2Percent,
        )

        val colWidth = CONTENT_WIDTH / 4
        rows.forEachIndexed { i, (label, value) ->
            val x = MARGIN + i * colWidth
            cursor.canvas.drawText(label, x, cursor.y, labelPaint)
            cursor.canvas.drawText(value, x, cursor.y + 20f, valuePaint)
        }
        cursor.y += 44f

        rangeBreakdown.forEachIndexed { i, (label, percent) ->
            val x = MARGIN + i * colWidth
            cursor.canvas.drawText(label, x, cursor.y, labelPaint)
            cursor.canvas.drawText("%.0f%%".format(percent), x, cursor.y + 20f, valuePaint)
        }
        cursor.y += 36f

        val footnote = Paint().apply { color = MUTED_TEXT; textSize = 11f; isAntiAlias = true }
        cursor.canvas.drawText(
            "${metrics.readingsCount} readings across %.1f days".format(metrics.daysOfData),
            MARGIN, cursor.y, footnote
        )
        cursor.y += 20f
    }

    private fun drawCoverageWarning(cursor: Cursor, metrics: AgpMetrics) {
        val warningPaint = Paint().apply { color = WARNING_COLOR; textSize = 12f; isAntiAlias = true; isFakeBoldText = true }
        val message = if (metrics.isBelowMinimumUsableCoverage) {
            "Only %.1f days of data in this range - too little to be reliable (7 days minimum, 14+ recommended by the AGP standard)."
                .format(metrics.daysOfData)
        } else {
            "Only %.1f days of data in this range - below the 14 days the AGP standard recommends for full reliability."
                .format(metrics.daysOfData)
        }
        wrapText("⚠ $message", warningPaint, CONTENT_WIDTH).forEach { line ->
            cursor.canvas.drawText(line, MARGIN, cursor.y, warningPaint)
            cursor.y += 16f
        }
        cursor.y += 4f
    }

    /** Greedy word-wrap to fit [maxWidth] - the coverage warning is the only
     *  text long enough to risk overflowing the page margin, so this doesn't
     *  need to be any more general than that. */
    private fun wrapText(text: String, paint: Paint, maxWidth: Float): List<String> {
        val words = text.split(" ")
        val lines = mutableListOf<String>()
        var current = StringBuilder()
        for (word in words) {
            val candidate = if (current.isEmpty()) word else "$current $word"
            if (paint.measureText(candidate) > maxWidth && current.isNotEmpty()) {
                lines.add(current.toString())
                current = StringBuilder(word)
            } else {
                current = StringBuilder(candidate)
            }
        }
        if (current.isNotEmpty()) lines.add(current.toString())
        return lines
    }

    /** Small color-key strip explaining what the chart line/band colors mean -
     *  shown on both variants since the line itself is colored regardless of
     *  showAnnotations. Swatch colors come from GlucoseReportChartRenderer's
     *  SEVERITY_LEGEND, which is built from the exact same color function the
     *  chart draws with, so this can't drift out of sync with the curve. */
    private fun drawColorLegend(cursor: Cursor) {
        cursor.ensureSpace(20f)
        val labelPaint = Paint().apply { color = MUTED_TEXT; textSize = 10f; isAntiAlias = true }
        val swatchSize = 10f
        var x = MARGIN
        val baselineY = cursor.y
        GlucoseReportChartRenderer.SEVERITY_LEGEND.forEach { (label, color) ->
            val swatchPaint = Paint().apply { this.color = color }
            cursor.canvas.drawRect(x, baselineY - swatchSize, x + swatchSize, baselineY, swatchPaint)
            val textX = x + swatchSize + 4f
            cursor.canvas.drawText(label, textX, baselineY, labelPaint)
            x = textX + labelPaint.measureText(label) + 16f
        }
        cursor.y += 24f
    }

    /** Numbered legend lines matching the numbered markers on the chart -
     *  same source (GlucoseReportChartRenderer.buildEventMarkers) as the
     *  chart itself drew, so the numbers always agree. Spills onto
     *  additional page(s) if the event list is long. */
    private fun drawEventLegend(cursor: Cursor, events: List<com.aheadt1d.app.events.UserEvent>) {
        if (events.isEmpty()) return

        val headingPaint = Paint().apply { color = Color.BLACK; textSize = 14f; isAntiAlias = true; isFakeBoldText = true }
        cursor.ensureSpace(24f)
        cursor.canvas.drawText("Event log", MARGIN, cursor.y, headingPaint)
        cursor.y += 20f

        val linePaint = Paint().apply { color = Color.BLACK; textSize = 12f; isAntiAlias = true }
        GlucoseReportChartRenderer.buildEventMarkers(events).forEach { marker ->
            cursor.ensureSpace(18f)
            cursor.canvas.drawText(GlucoseReportChartRenderer.legendLineFor(marker), MARGIN, cursor.y, linePaint)
            cursor.y += 18f
        }
    }

    private fun dateRangeSlug(start: Instant, end: Instant): String {
        val zone = ZoneId.systemDefault()
        return "${SLUG_FORMATTER.withZone(zone).format(start)}_to_${SLUG_FORMATTER.withZone(zone).format(end)}"
    }

    /** Tracks the current draw position within a PdfDocument, starting new
     *  pages as content overflows - PdfDocument itself has no auto-flow
     *  layout, so this is the minimal bookkeeping needed for the event legend
     *  (the only section that can be arbitrarily long) to safely spill over. */
    private class Cursor(private val document: PdfDocument, initialPageNumber: Int) {
        private var pageNumber = initialPageNumber
        private var page: PdfDocument.Page = document.startPage(
            PdfDocument.PageInfo.Builder(PAGE_WIDTH, PAGE_HEIGHT, pageNumber).create()
        )
        var canvas = page.canvas
            private set
        var y = MARGIN + 12f

        fun ensureSpace(needed: Float) {
            if (y + needed > PAGE_HEIGHT - MARGIN) {
                document.finishPage(page)
                pageNumber += 1
                page = document.startPage(PdfDocument.PageInfo.Builder(PAGE_WIDTH, PAGE_HEIGHT, pageNumber).create())
                canvas = page.canvas
                y = MARGIN + 12f
            }
        }

        fun finishPage() = document.finishPage(page)
    }

    private val DATE_FORMATTER = DateTimeFormatter.ofPattern("MMM d, yyyy")
    private val TIMESTAMP_FORMATTER = DateTimeFormatter.ofPattern("MMM d, yyyy h:mm a")
    private val SLUG_FORMATTER = DateTimeFormatter.ofPattern("yyyy-MM-dd")
}
